[package]
name = "strategize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graph_builder= "0.3.0"
dashmap="5.4.0"
num-traits="0.2.15"
spaces="6.0.0"